// Markdown.tsx — rich message rendering: GitHub-flavored markdown, KaTeX math
// ($…$ / $$…$$ / \(…\) / \[…\]), and syntax-highlighted fenced code blocks, plus
// styled inline code.
//
// Security (NF-1): react-markdown v9 does NOT render raw HTML (no rehype-raw),
// so model output can't inject markup. KaTeX/highlight output is generated by
// the trusted rehype plugins into the React tree, never via innerHTML of raw
// model text. `throwOnError: false` keeps partial math during streaming from
// crashing the render.
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import rehypeHighlight from 'rehype-highlight';
import 'katex/dist/katex.min.css';
import 'highlight.js/styles/github.css';

const REMARK = [remarkGfm, remarkMath];
const REHYPE = [[rehypeKatex, { throwOnError: false }], rehypeHighlight];

/**
 * Normalize the LaTeX delimiters LLMs commonly emit (`\(…\)`, `\[…\]`) into the
 * `$…$` / `$$…$$` that remark-math understands. Done outside fenced code so we
 * don't rewrite literal backslashes inside code samples.
 */
function normalizeMath(src: string): string {
  const parts = src.split(/(```[\s\S]*?```|`[^`]*`)/g);
  return parts
    .map((seg, i) => {
      if (i % 2 === 1) return seg; // code span/fence — leave untouched
      return (
        seg
          // \[ … \] -> block display math (own lines so remark-math sees a block)
          .replace(/\\\[([\s\S]+?)\\\]/g, (_m, x: string) => `\n\n$$\n${x.trim()}\n$$\n\n`)
          // \( … \) -> inline math
          .replace(/\\\(([\s\S]+?)\\\)/g, (_m, x: string) => `$${x.trim()}$`)
          // single-line $$ … $$ -> block form, so it renders in DISPLAY mode
          // (true display style: limits under ∑/∫, centered). A $$ already in
          // block form starts with a newline and is left untouched.
          .replace(
            /\$\$([^\n$][\s\S]*?)\$\$/g,
            (_m, x: string) => `\n\n$$\n${x.trim()}\n$$\n\n`
          )
      );
    })
    .join('');
}

export function Markdown({ text }: { text: string }) {
  return (
    <div className="md">
      <ReactMarkdown
        remarkPlugins={REMARK}
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        rehypePlugins={REHYPE as any}
      >
        {normalizeMath(text)}
      </ReactMarkdown>
    </div>
  );
}
